### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by nicotravassos** [JamesSkemp/battle-inf#11]
Hi @JamesSkemp,

Has this project been shelved?

**Comment by JamesSkemp** [comment]
Good question.

I wouldn't say it's shelved, but lack of development time means I've been focusing on developing my own battle system, instead of trying to make this one responsive and using TypeScript. The more I dug into the battle system the more I thought the late game might be a bit of a bog.

The biggest issue, though, was dealing with the layout issues. Whatever was causing breaking issues with a certain number of equipment was driving me crazy. 🗡 

Does that answer your question?

**Comment by nicotravassos** [comment]
Yes @JamesSkemp Thanks
